### ISSUE TITLE
Dubius ownership

### ISSUE THREAD

**Issue by HelenOne** [Hexlet/hexlet-exercise-kit#49]
![image](https://github.com/Hexlet/hexlet-exercise-kit/assets/37748853/2da14e96-47c4-466e-bb54-c4137dbb0341)

https://github.com/Hexlet/hexlet-exercise-kit/blob/f48b0fc3f2aadf88a5d68e5c7f08dc004e792c2e/repo-downloader/exe/download#L4C5-L4C5 - во время парнокодинга выяснили, что в этой строке происходит ошибка, потому что идет запрос наверх и почему-то ожидается гит репозиторий

решили это инициализацией гит репозитория внутри repo-downloader

**Comment by corsicanec82** [comment]
Пофиксил
https://github.com/Hexlet/hexlet-exercise-kit/commit/22b7ef429fdf2aa061dd06dba8ac30482cfbc375
На верхнем уровне вообще не обязательно должен быть гит репозиторий, он использовался только для определения списка файлов которые должны попасть в гем

**Comment by corsicanec82** [comment]
Пофиксил
https://github.com/Hexlet/hexlet-exercise-kit/commit/22b7ef429fdf2aa061dd06dba8ac30482cfbc375
На верхнем уровне вообще не обязательно должен быть гит репозиторий, он использовался только для определения списка файлов которые должны попасть в гем
